# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5rRlYWcU1KXo-n-mFoYWd7I_-g0MPTV
"""

def factorial(n):
  if n<=1:
    return 1
  return n*factorial(n-1)
n=5
print(f"factorial of {n} is {factorial(n)}")
